### ISSUE TITLE
CELS_github\model\CELS_Model.py", line 372, in fit_n_1

### ISSUE THREAD

**Issue by shouhengtuo** [RunlongYu/CELS#5]
CELS_github\model\CELS_Model.py", line 372, in fit_n_1
    torch.from_numpy(y))
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.

**Comment by psycho-demon** [comment]
May I ask if the dataset for your experiment is a sample file from criteo? The preprocessing code has some bugs with this sample file, which I'm currently working on fixing. Please try the full criteo dataset.

**Comment by shouhengtuo** [comment]
Thank you!



At 2023-08-28 19:23:48, "徐翔" ***@***.***> wrote:

May I ask if the dataset for your experiment is a sample file from criteo? The preprocessing code has some bugs with this sample file, which I'm currently working on fixing. Please try the full criteo dataset.
